from typing import Dict
from datetime import datetime

class DocumentationGenerator:
    @staticmethod
    def generate_readme(analysis: Dict) -> str:
        readme = f"""# {analysis['project_name']}

## Project Summary
{analysis['summary']}

## Tech Stack
**Primary Language:** {analysis['detected_language']}
"""
        
        if analysis.get('framework'):
            readme += f"**Framework:** {analysis['framework']}\n"
        
        if analysis['tech_stack']:
            readme += "\n**Additional Technologies:**\n"
            for key, value in analysis['tech_stack'].items():
                readme += f"- {key.replace('_', ' ').title()}: {value}\n"
        
        readme += f"""
## Project Structure
```
{analysis['folder_structure']}
```

"""
        
        if analysis.get('api_endpoints'):
            readme += "## API Endpoints\n"
            for endpoint in analysis['api_endpoints'][:20]:
                readme += f"- `{endpoint}`\n"
            readme += "\n"
        
        readme += f"""## Getting Started

### Prerequisites
- {analysis['detected_language']} installed on your system
"""
        
        if analysis.get('framework'):
            readme += f"- {analysis['framework']} framework\n"
        
        readme += """
### Installation
1. Clone the repository
2. Install dependencies
3. Run the application

## Documentation Generated
This documentation was automatically generated by Smart Documentation Generator.

**Generated on:** """ + datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")
        
        return readme
